# Site settings
title: CBusJS
email:
description: "Columbus JavaScript User Group"
baseurl: ""
url: "https://cbusjs.github.io"
twitter_username: cbusjs
github_username:  cbusjs
paginate: 3

# Build settings
markdown: kramdown
permalink: /:month-:day-:year/:title.html
