# Site settings
title: ColumbusJS
description: "Know some JavaScript? Want to know more? Join us at our monthly meeting or online on Discord as we discuss JavaScript and it's related technologies."
url: http://columbusjs.org
email: guy@guyroyse.com
twitter: https://twitter.com/cbusjs
github: https://github.com/columbusjs
twitch: https://www.twitch.tv/ColumbusJS
discord: https://discord.gg/SpHNwXS
youtube: https://www.youtube.com/channel/UCcoPThmAqKoedt7AVHl0elw
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sass-converter
  - kramdown
  - rouge
markdown: kramdown
highlighter: rouge
timezone: America/Detroit
safe: false
paginate: 3
permalink: /:month-:day-:year/:title.html
future: true
