# Site settings
title: CBusJS
email: 
description: "Columbus JavaScript User Group"
baseurl: ""
url: "http://0.0.0.0:4000"
twitter_username: cbusjs
github_username:  cbusjs
paginate: 5

# Build settings
markdown: kramdown
permalink: /:month-:day-:year/:title.html
